"""Schema dataclasses exchanged between decoupled HyperAgent modules."""

from hyperagent.schemas.agent import (
    AgentActionRun,
    AgentActionStep,
    AgentToolCall,
    AgentToolResult,
    CodingAgentRun,
    GeneralAgentRun,
    MultiAgentRoleRun,
    MultiAgentTaskRun,
    RepoFileContext,
    RepoSnapshot,
    SlashCommandSpec,
    TodoItem,
    TodoList,
)
from hyperagent.schemas.channels import (
    ChannelBotConfig,
    ChannelEventResult,
    ChannelInboundMessage,
    ChannelOutboundMessage,
)
from hyperagent.schemas.dataset import DatasetAudit
from hyperagent.schemas.conversation import (
    ConversationMessage,
    ConversationSession,
    ConversationSummary,
)
from hyperagent.schemas.evaluation import EvaluationReport
from hyperagent.schemas.experiment import (
    ExperimentPlan,
    ExperimentResult,
    ExperimentSuiteResult,
    ModelConfig,
    PreprocessingConfig,
    SplitConfig,
)
from hyperagent.schemas.literature import LiteraturePaper, LiteratureSearchResult
from hyperagent.schemas.llm import (
    AgentTurnTiming,
    AgentTurnResult,
    LLMMessage,
    LLMProviderSpec,
    LLMRequest,
    LLMResponse,
)
from hyperagent.schemas.recommendation import ModelCandidate, ModelRecommendation
from hyperagent.schemas.integrations import (
    MaterializationResult,
    MCPServerSpec,
    ObsidianNote,
    PromptTemplate,
    SkillSpec,
)
from hyperagent.schemas.research import (
    AblationStudy,
    AblationVariant,
    AutoExperimentAgenda,
    DecisionRecord,
    EvidenceItem,
    ExperimentCandidate,
    ExperimentCouncilDecision,
    ExperimentCouncilRoleRun,
    ExperimentCouncilRun,
    ExperimentCouncilVote,
    ExperimentCycle,
    ExperimentDiagnosis,
    ModuleProposal,
    ParameterProposal,
)
from hyperagent.schemas.runtime import ProjectConfig, ResearchTask, WorkspaceStatus
from hyperagent.schemas.spectral import SpectralReport

__all__ = [
    "DatasetAudit",
    "AblationStudy",
    "AblationVariant",
    "AgentActionRun",
    "AgentActionStep",
    "AgentTurnTiming",
    "AgentTurnResult",
    "AgentToolCall",
    "AgentToolResult",
    "AutoExperimentAgenda",
    "CodingAgentRun",
    "ChannelBotConfig",
    "ChannelEventResult",
    "ChannelInboundMessage",
    "ChannelOutboundMessage",
    "GeneralAgentRun",
    "MultiAgentRoleRun",
    "MultiAgentTaskRun",
    "ConversationMessage",
    "ConversationSession",
    "ConversationSummary",
    "DecisionRecord",
    "EvaluationReport",
    "EvidenceItem",
    "ExperimentCandidate",
    "ExperimentCouncilDecision",
    "ExperimentCouncilRoleRun",
    "ExperimentCouncilRun",
    "ExperimentCouncilVote",
    "ExperimentCycle",
    "ExperimentDiagnosis",
    "ExperimentPlan",
    "ExperimentResult",
    "ExperimentSuiteResult",
    "LiteraturePaper",
    "LiteratureSearchResult",
    "LLMMessage",
    "LLMProviderSpec",
    "LLMRequest",
    "LLMResponse",
    "MaterializationResult",
    "MCPServerSpec",
    "ModelCandidate",
    "ModelConfig",
    "ModuleProposal",
    "ModelRecommendation",
    "ObsidianNote",
    "ParameterProposal",
    "PreprocessingConfig",
    "PromptTemplate",
    "ProjectConfig",
    "RepoFileContext",
    "RepoSnapshot",
    "SlashCommandSpec",
    "ResearchTask",
    "SkillSpec",
    "SpectralReport",
    "SplitConfig",
    "TodoItem",
    "TodoList",
    "WorkspaceStatus",
]
