#!/usr/bin/env bash
set -euo pipefail

ENV_NAME="${1:-HyperAgent}"
OUTPUT="${2:-environment.txt}"

{
  echo "# HyperAgent conda package snapshot"
  echo "# Generated by: scripts/update_environment_txt.sh ${ENV_NAME} ${OUTPUT}"
  echo "# Update cadence: after dependency changes and before stage commits."
  echo "# Recreate the exact package list with:"
  echo "#   conda create -n HyperAgent --file environment.txt"
  echo
  conda list -n "${ENV_NAME}" --export
} > "${OUTPUT}"

echo "Wrote ${OUTPUT} from conda env ${ENV_NAME}"
